version: '2'

services:
  openresty:
    build: ./
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
      - "./src:/code"
    environment:
      BITBUCKET_MATTERMOST_URL: '<bitbucket-mattermost-hook-url>'
      SENTRY_MATTERMOST_URL: '<sentry-mattermost-hook-url>'
